TRUNCATE TABLE recipes;

INSERT INTO recipes
VALUES ('1',
        '1',
        'Заголовок',
        'Title',
        'Intro is here in this column',
        'Интро здесь в этой колонке',
        'Ингридиенты в этой колонке тоже',
        'Ingredients are in this column as well',
        'Рыбатекст используется дизайнерами, проектировщиками и фронтендерами, когда нужно быстро заполнить макеты или прототипы содержимым. Это тестовый контент',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vel sapien dui. Cras ultricies lacinia quam nec vestibulum. Curabitur suscipit tincidunt est blandit viverra',
        '1',
        '1',
        '1',
        '1',
        '1',
        '1',
        '1',
        'slug',
        '33',
        'default.jpg',
        NOW(),
        NOW());