version: '3'

services:
    reciper_go_db:
        image: mysql:8.0
        container_name: reciper_go_db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 111111
            MYSQL_DATABASE: reciper
        ports:
            - 2222:3306
        volumes:
            - ./db/storage:/var/lib/mysql
        networks:
            - reciper_net

    reciper_go_nginx:
        container_name: reciper_go_nginx
        image: serhiicho/reciper_go:nginx
        build:
            context: ./frontend
            dockerfile: Dockerfile
        networks:
            - reciper_net
        volumes:
            - ./frontend/dist:/app/dist
            - ./backend/storage:/app/dist/storage
        environment:
            GO111MODULE: "on"
        ports:
            - 8000:80
        depends_on:
            - reciper_go
            - reciper_go_db

    reciper_go:
        container_name: reciper_go
        image: serhiicho/reciper_go:go
        build:
            context: ./backend
            dockerfile: Dockerfile
        networks:
            - reciper_net
        ports:
            - 8080:8080
        links:
            - reciper_go_db
        depends_on:
            - reciper_go_db

    reciper_go_pa:
        image: phpmyadmin/phpmyadmin
        container_name: reciper_go_pa
        environment:
            - PMA_ARBITRARY=1
        restart: always
        ports:
            - 1221:80
        depends_on:
            - reciper_go_db
        networks:
            - reciper_net

networks:
    reciper_net:
        driver: bridge